AuthService_PostmanTests
lanit-students/TradingStation pull request #102
Opened 2020-04-17 14:27 UTC by DenisKrivoruchko11

2020-04-17 14:30 UTC, DanilFadeeev approved these changes

2020-04-17 15:10 UTC, Maksim-Trolina approved these changes

2020-04-17 16:24 UTC, ifelseelif requested changes
I think you should  make 1 more request, where do you create user with this email and password, because without it tests fall down

2020-04-17 18:06 UTC, ifelseelif approved these changes

2020-04-18 08:27 UTC, LK777LK approved these changes

2020-04-18 08:53 UTC, merged