add validator in user service and tests for it
lanit-students/TradingStation pull request #63
Opened 2020-04-05 21:17 UTC by DanilFadeeev

2020-04-05 21:38 UTC, Cerberous007 reviewed
Please rename pull request. If you have any questions, check out our code convention.

2020-04-05 21:44 UTC, Cerberous007 reviewed
What happens to this branch? You should make merge develop into your branch

2020-04-05 21:53 UTC, DanilFadeeev commented
> What happens to this branch? You should make merge develop into your branch

i did

2020-04-05 22:28 UTC, dTarasova commented
Name is still doesn't match code convention :)

Sorry , I don't get it . A lot of changed files and I think some work repeats existing files

2020-04-05 22:35 UTC, dTarasova requested changes

2020-04-05 22:35 UTC, dTarasova commented on Common/DTO/BrokerRequests/InternalDeleteUserRequest.cs
> +        public Guid UserIdCredential { get; set; }
This aready has to be UserId :)

2020-04-05 22:35 UTC, dTarasova commented on Services/UserService/Controllers/UsersController.cs
> +            CreateUserRequesValidator validator = new CreateUserRequesValidator();
What? Nononono
We already have data validation in createUserCommand
Why do you have to write all logic here?!

2020-04-05 22:35 UTC, dTarasova commented on SingUpModelValidationTests/UnitTest1.cs
> +    public class Tests
Are you sure that we need these tests?

2020-04-05 22:35 UTC, dTarasova commented on Tests/AuthServiceTests/Validators/CreateUserRequestValidatorTests.cs
> +namespace AuthenticationServiceTests.Validators
In Authentification. CreateUserRequestTests. Are you seriously?

2020-04-05 22:35 UTC, dTarasova commented on Tests/AuthServiceTests/Validators/CreateUserRequestValidatorTests.cs
> +namespace AuthenticationServiceTests.Validators
Also, we already have sth like that in  user service" createuserrequestvalidator

2020-04-06 09:05 UTC, nmamro requested changes
Please, check why **Files changed** list is so strange

2020-04-06 09:05 UTC, nmamro commented on Common/DTO/BrokerRequests/InternalDeleteUserRequest.cs
> +        public Guid UserIdCredential { get; set; }
> This aready has to be UserId :)

Technically, this hasn't been pushed to develop yet, has it?

2020-04-06 09:05 UTC, zzzloba commented on Common/DTO/ErrorResponse.cs
> +﻿using System;
I don't understand why these are in **Files changed** list, any ideas?

2020-04-06 09:05 UTC, zzzloba commented on PostmanTests/UserService.postman_collection.json
>  {
I don't understand why these are in **Files changed** list, any ideas?

2020-04-06 10:46 UTC, closed without merging